### PR TITLE
Feature/67

### PR DESCRIPTION
**Pull request by ReginaBorisova**
#67 Github Links
    -Added links for 3 existing projects on GitHub;

Request to approve

### CODE REVIEW

**Review by sashas777 — CHANGES_REQUESTED** [review]
@ReginaBorisova 
- File template/menu.phtml shouldn;t be part of this request
- Please add commit message "resolve with task #" so when it merges task automatically closes.

**Comment by ReginaBorisova** [comment]
#67 Github links. Work done : 
      - commited with "resolve with task #";
      - removed unnecessary space;
      - commited without template/menu.phtml
      
Request to approve

**Comment by sashas777** [comment]
@ReginaBorisova 
File template/menu.phtml shouldn;t be part of this request

**Comment by ReginaBorisova** [comment]
Resolve #67. 
    -pulled from the master, merge branch 'master';
    -commit without template/menu.phtml
Kindly request to approve

**Review by sashas777 — APPROVED** [review]

**Pull request merged**
