### PR TITLE
Feature/27

### PR DESCRIPTION
**Pull request by ReginaBorisova**
Code Style Refactoring #27. Refactored code with the correct code styling #27 after reading provided material. Checked for proper indentation and spacing of the following files: index.php, work.php, about.php, contact.php.  Fixed the conflict I had on head.phtml file.

### CODE REVIEW

**Review by sashas777 — CHANGES_REQUESTED** [review]
@ReginaBorisova 
Link the task ticket for this PR, please. Its not clear what this PR is for.

**Review by sashas777 — CHANGES_REQUESTED** [review]
@ReginaBorisova 
Link the task ticket for this PR, please. Its not clear what this PR is for.

**Comment by ReginaBorisova** [comment]
Code Style Refactoring #27. Checked for proper spacing and indentation of the following files: index.php, work.php, about.php, contact.php.

**Comment by sashas777** [comment]
@ReginaBorisova
Link the task ticket for this PR, please. Its not clear what this PR is for.

**Review by sashas777 — CHANGES_REQUESTED** [review]
- [x] We now have file for all functions so needed to cleanup code and have all functions in one file https://github.com/ReginaBorisova/portfolio/blob/214bc315ea88320a8a0f01b9f629dc58082cdee6/index.php#L19
- [x] https://github.com/ReginaBorisova/portfolio/blob/214bc315ea88320a8a0f01b9f629dc58082cdee6/calculation.php#L16
- [x] Should it be part of variables? https://github.com/ReginaBorisova/portfolio/blob/214bc315ea88320a8a0f01b9f629dc58082cdee6/lesson.php#L11
- [x] Require once and PHP open (<?php) and close tag can be on the same line (Check all files) https://github.com/ReginaBorisova/portfolio/blob/214bc315ea88320a8a0f01b9f629dc58082cdee6/work.php#L7
- [x] In order to better organize the code you may want to move variables into the functions directory. This way we separate pages from PHP code for variables and functions that are defined globally.
- [x] When you have if, foreach or other statements like this in the template file (template is file that have HTML and PHP code that used to to present information) its better to have it in the alternative form to have it with correct padding form readable form. https://www.php.net/manual/en/control-structures.alternative-syntax.php 
- [x] https://devtut.github.io/php/alternative-syntax-for-control-structures.html#alternative-if-else-statement
- [x] READ: https://www.javatpoint.com/php-mvc-architecture
- [x] Extra spaces: https://github.com/ReginaBorisova/portfolio/blob/214bc315ea88320a8a0f01b9f629dc58082cdee6/css/main.css#L299
- [x] Add DockBlock for functions: https://docs.phpdoc.org/guide/getting-started/what-is-a-docblock.html  https://www.jetbrains.com/help/phpstorm/phpdoc-comments.html

**Comment by ReginaBorisova** [comment]
Resolved #27 Code Style Refactoring. Next changes are made:

                  - moved all functions into one file;
                  - moved $myArray from lesson.php to variables.php;
                  - fixed require_once and PHP open (<?php) and close tag on the same line in each file;
                  - moved variables.php into functions/variables.php directory;
                  - rewrite if/foreach and other statement in all template/file.phtml in the way to satisfy Alternative Syntax for Control 
                    Structures;
                  - have read the required articles;
                  - removed extra space in [portfolio/css/main.css];
                  - added DockBlock for functions located in functions/functions.php;
                  
Kindly request to review the changes I have made and provide any feedback or suggestions

**Review by sashas777 — CHANGES_REQUESTED** [review]
- [ ] This is not a function (Should it be in variables?): https://github.com/ReginaBorisova/portfolio/blob/23bc28b407a1bf09c8b94cdb35ce287f6694bb2d/functions/functions.php#LL32C1-L32C63

**Review by sashas777 — CHANGES_REQUESTED** [review]
- [ ] Foreach isn't modified https://github.com/ReginaBorisova/portfolio/blob/23bc28b407a1bf09c8b94cdb35ce287f6694bb2d/index.php#L20

**Comment by ReginaBorisova** [comment]
Requested changes made in #27 Code Style Refactoring. Next changes are made:
      - moved $whoParam from functions.php to variables.php;
      - modified 'foreach' statement according Alternative syntax for control structures, based on provided material form : 
                         **Alternative foreach statement**
                             <?php                             
                                foreach ($collection as $item):
                                   do_something($item);
                               endforeach;
                               ?>

                               <?php foreach ($collection as $item): ?>
                                   <p>Do something in HTML with <?php echo $item; ?></p>
                               <?php endforeach; ?>

Kindly request close the pull request if satisfied with the results.

**Review by sashas777 — APPROVED** [review]

**Pull request merged**
